name: 채널 신고
description: AI Slop 의심 채널을 신고합니다
title: "[신고] @채널핸들 - 채널명"
labels: ["신고"]
body:
  - type: input
    id: channel_handle
    attributes:
      label: 채널 핸들 (@handle)
      placeholder: "@example_channel"
    validations:
      required: true
  - type: input
    id: channel_name
    attributes:
      label: 채널명
      placeholder: "예시 채널"
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: 카테고리
      options:
        - news (가짜 뉴스/속보)
        - celebrity (연예인 AI 영상)
        - finance (투자/재테크 사기)
        - health (건강/의료 허위정보)
        - other (기타)
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: 증거
      description: 해당 채널이 AI Slop인 이유 (영상 링크 첨부)
      placeholder: |
        - 영상 링크: https://youtube.com/watch?v=...
        - AI 음성 사용
        - 하루 20개 이상 업로드
    validations:
      required: true
